echo "ON personas_crud"
gnome-terminal --tab --command="sh $CAMPUS/personas_crud.sh"
echo "ON ubicaciones_crud"
gnome-terminal --tab --command="sh $CAMPUS/ubicaciones_crud.sh"
echo "ON ente_crud"
gnome-terminal --tab --command="sh $CAMPUS/ente_crud.sh"
echo "ON documentos_crud"
gnome-terminal --tab --command="sh $CAMPUS/documentos_crud.sh"
echo "ON formacion_academica_crud"
gnome-terminal --tab --command="sh $CAMPUS/formacion_academica_crud.sh"
echo "ON experiencia_laboral_crud"
gnome-terminal --tab --command="sh $CAMPUS/experiencia_laboral_crud.sh"
echo "ON core_crud"
gnome-terminal --tab --command="sh $CAMPUS/core_crud.sh"
echo "ON programa_academico_crud"
gnome-terminal --tab --command="sh $CAMPUS/programa_academico_crud.sh"
echo "ON admisiones_crud"
gnome-terminal --tab --command="sh $CAMPUS/admisiones_crud.sh"
echo "ON idiomas_crud"
gnome-terminal --tab --command="sh $CAMPUS/idiomas_crud.sh"
echo "ON sesiones_crud"
gnome-terminal --tab --command="sh $CAMPUS/sesiones_crud.sh"
echo "ON forms_management_crud"
gnome-terminal --tab --command="sh $CAMPUS/forms_management_crud.sh"
echo "ON organizacion_crud"
gnome-terminal --tab --command="sh $CAMPUS/organizacion_crud.sh"
echo "ON produccion_academica_crud"
gnome-terminal --tab --command="sh $CAMPUS/produccion_academica_crud.sh"
echo "ON matricula_descuentos_crud"
gnome-terminal --tab --command="sh $CAMPUS/matricula_descuentos_crud.sh"
echo "ON campus_mid"
gnome-terminal --tab --command="sh $CAMPUS/campus_mid.sh"