echo "Detener API's"
killall personas_crud
killall campus_mid
killall core_crud
killall documentos_crud
killall ente_crud
killall experiencia_laboral_crud
killall formacion_academica_crud
killall programa_academico_crud
killall ubicaciones_crud
killall admisiones_crud
killall idiomas_crud
killall sesiones_crud
killall forms_management_crud